import { Brand } from "@/types/brand";

const brandsData: Brand[] = [
  {
    id: 6,
    name: "React",
    href: "https://formbold.com",
    image: "/images/brands/react.svg",
    imageLight: "/images/brands/react.svg",
    category: "frontend",
  },
  {
    id: 13,
    name: "Next JS",
    href: "",
    image: "/images/brands/next-js.svg",
    imageLight: "/images/brands/next-js.svg",
    category: "frontend",
  },
  {
    id: 14,
    name: "Express JS",
    href: "",
    image: "/images/brands/express-js.svg",
    imageLight: "/images/brands/express-js.svg",
    category: "backend",
  },
  {
    id: 15,
    name: "Rsuite",
    href: "",
    image: "/images/brands/rsuite.png",
    imageLight: "/images/brands/rsuite.png",
    category: "frontend",
  },
  {
    id: 16,
    name: "Bootstrap",
    href: "",
    image: "/images/brands/Bootstrap.svg",
    imageLight: "/images/brands/Bootstrap.svg",
    category: "frontend",
  },
  {
    id: 17,
    name: "Tailwind",
    href: "",
    image: "/images/brands/Tailwind.svg",
    imageLight: "/images/brands/Tailwind.svg",
    category: "frontend",
  },
  {
    id: 2,
    name: "HTLM",
    href: "",
    image: "/images/brands/html.svg",
    imageLight: "/images/brands/html.svg",
    category: "frontend",
  },
  {
    id: 10,
    name: "Css",
    href: "",
    image: "/images/brands/css.svg",
    imageLight: "/images/brands/css.svg",
    category: "frontend",
  },
  {
    id: 4,
    name: "JavaScript",
    href: "",
    image: "/images/brands/js.svg",
    imageLight: "/images/brands/js.svg",
    category: "frontend",
  },
  {
    id: 5,
    name: "Redux",
    href: "",
    image: "/images/brands/redux.svg",
    imageLight: "/images/brands/redux.svg",
    category: "frontend",
  },
  {
    id: 12,
    name: "Material UI",
    href: "",
    image: "/images/brands/material-ui.svg",
    imageLight: "/images/brands/material-ui.svg",
    category: "frontend",
  },

  {
    id: 7,
    name: "Node js",
    href: "",
    image: "/images/brands/node-js.svg",
    imageLight: "/images/brands/node-js.svg",
    category: "backend",
  },

  {
    id: 11,
    name: "Mysql",
    href: "",
    image: "/images/brands/mysql.svg",
    imageLight: "/images/brands/mysql.svg",
    category: "backend",
  },

  {
    id: 3,
    name: "Android",
    href: "",
    image: "/images/brands/android.svg",
    imageLight: "/images/brands/android.svg",
    category: "native",
  },
  {
    id: 12,
    name: "ios",
    href: "",
    image: "/images/brands/apple.svg",
    imageLight: "/images/brands/apple.svg",
    category: "native",
  },

  {
    id: 8,
    name: "Git",
    href: "",
    image: "/images/brands/git.svg",
    imageLight: "/images/brands/git.svg",
    category: "devops",
  },
  {
    id: 9,
    name: "Github",
    href: "",
    image: "/images/brands/github.svg",
    imageLight: "/images/brands/github.svg",
    category: "devops",
  },
  {
    id: 10,
    name: "Visual Studio Code",
    href: "",
    image: "/images/brands/vscode.svg",
    imageLight: "/images/brands/vscode.svg",
    category: "othertools",
  },
  {
    id: 11,
    name: "Postman",
    href: "",
    image: "/images/brands/postman.svg",
    imageLight: "/images/brands/postman.svg",
    category: "othertools",
  },

  {
    id: 1,
    name: "Firebase",
    href: "",
    image: "/images/brands/firebase.svg",
    imageLight: "/images/brands/firebase.svg",
    category: "backend",
  },
];

export default brandsData;
